import os
import shutil
import subprocess
import json
from colorama import Fore, Style
from .base import BaseCommand

class InstallCommand(BaseCommand):
    _modules_dir = ".dcpm/modules"

    def run(self, params):
        if not self.dcpm_validation(): return

        config = self.get_dcpm_config()
        if not config: return

        to_process = config.get("dependencies", {}).copy()
        processed = set()
        
        print(f"{Fore.CYAN}{Style.BRIGHT}--- Recursive Installation ---{Style.RESET_ALL}")

        while to_process:
            alias = list(to_process.keys())[0]
            info = to_process.pop(alias)
            
            if alias in processed:
                continue

            success = self._install_if_missing(alias, info)
            
            if success:
                processed.add(alias)
                
                sub_deps = self._get_sub_dependencies(alias)
                for sub_alias, sub_info in sub_deps.items():
                    if sub_alias not in processed:
                        if sub_alias in to_process:
                            if to_process[sub_alias]['version'] != sub_info['version']:
                                print(f"{Fore.YELLOW}⚠ Version mismatch for {sub_alias}. Using {to_process[sub_alias]['version']}{Fore.RESET}")
                        else:
                            to_process[sub_alias] = sub_info

        self._prune_unused(processed)
        
        self._update_full_cmake(processed)

        print(f"\n{Fore.GREEN}{Style.BRIGHT}✔ System synchronized ({len(processed)} modules installed).{Style.RESET_ALL}")

    def _get_sub_dependencies(self, alias):
        sub_config_path = os.path.join(self._modules_dir, alias, ".dcpm", "config.json")
        if os.path.exists(sub_config_path):
            try:
                with open(sub_config_path, "r") as f:
                    data = json.load(f)
                return data.get("dependencies", {})
            except Exception:
                return {}
        return {}

    def _install_if_missing(self, name, info):
        dest_path = os.path.join(self._modules_dir, name)
        
        if os.path.exists(dest_path):
            return True

        url = info.get("url")
        version = info.get("version")
        
        print(f"{Fore.BLUE}Installing {Style.BRIGHT}{name}{Style.RESET_ALL} ({version})...")
        
        try:
            cmd = ["git", "clone", "--depth", "1"]
            if version and version != "default":
                cmd += ["--branch", version]
            cmd += [url, dest_path]
            
            subprocess.run(cmd, check=True, capture_output=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"{Fore.RED}  → Error cloning {name}.{Fore.RESET}")
            if e.stderr:
                print(f"{Fore.WHITE}{e.stderr.decode().strip()}{Fore.RESET}")
            return False

    def _prune_unused(self, needed_libs):
        if not os.path.exists(self._modules_dir): return
        installed = set(os.listdir(self._modules_dir))
        to_delete = installed - needed_libs
        for folder in to_delete:
            print(f"{Fore.YELLOW}Pruning unused dependency: {folder}{Fore.RESET}")
            shutil.rmtree(os.path.join(self._modules_dir, folder))

    def _update_full_cmake(self, all_libs):
        cmake_path = ".dcpm/dcpm.cmake"
        lines = [
            "# This file is auto-generated by dcpm.",
            "# It includes all direct and indirect dependencies.",
            "\nset(DCPM_LIBRARIES \"\")\n"
        ]
        
        for lib in sorted(all_libs):
            lib_path = f".dcpm/modules/{lib}"
            lines.append(f"if(EXISTS \"${{CMAKE_SOURCE_DIR}}/{lib_path}/CMakeLists.txt\")")
            lines.append(f"    add_subdirectory({lib_path})")
            lines.append(f"    list(APPEND DCPM_LIBRARIES {lib})")
            lines.append("endif()\n")
            
        with open(cmake_path, "w") as f:
            f.write("\n".join(lines))

    def get_short_help(self):
        return "Synchronize installed modules with config.json."

    def get_long_help(self):
        return (f"Usage: {Fore.GREEN}dcpm install{Fore.RESET}\n\n"
                "Synchronizes the '.dcpm/modules/' directory with your configuration:\n"
                "  1. Downloads missing dependencies from Git.\n"
                "  2. Removes unused libraries from the modules folder.\n"
                "  3. Uses shallow cloning (--depth 1) for maximum performance.")
